stages:
- stage: Build
  jobs:
    - job: BuildLinux
      displayName: "Build Linux"
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
      - script: |
          sudo apt-get update -y
          sudo apt-get install -y g++-8
        displayName: Install GCC 8
      - script: |
          git submodule update --init --recursive
          mkdir build
          cd build
          g++ --version
          cmake .. -DCMAKE_CXX_COMPILER=g++-8
        displayName: Prepare build
      - script: |
          cd build
          make -j 4
        displayName: build
      - script: |
          ./build/gtest
        displayName: "Run tests"

- stage: Documentation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Documentation
    displayName: "Build + deploy documentation"
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        sudo apt-get install -y doxygen graphviz
      displayName: Apt install dependencies
    - script: |
        cd doc
        doxygen
      displayName: build doxygen
    - script: |
        cd doc/html
        git init
        git checkout --orphan gh-pages
        git add .
        git -c user.name='Azure' -c user.email='Azure' commit -m "Deploy xenium documentation to gh-pages"
        git push -f -q "https://mpoeter:$(GITHUB_TOKEN)@github.com/mpoeter/xenium.git" gh-pages
      displayName: publish GitHub pages
