#pool:
  #vmImage: 'Ubuntu-16.04', 'vs2017-win2016', 'macOS-10.13'

stages:
- stage: Build
  jobs:
    - job: BuildLinux
      displayName: "Build Linux"
      pool:
        vmImage: 'Ubuntu-16.04'
      steps:
      - script: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install -y g++-7
        displayName: Install GCC 7
      - script: |
          wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
          tar xzf boost_1_68_0.tar.gz
        displayName: Get boost
      - script: |
          git submodule update --init --recursive
          mkdir build
          cd build
          g++ --version
          cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DBOOST_ROOT=./boost_1_68_0
        displayName: Prepare build
      - script: |
          cd build
          make -j 4
        displayName: build
      - script: |
          ./build/gtest
        displayName: "Run tests"
        

    - job: WindowsCMake
      displayName: "Build Windows"
      pool:
        vmImage: vs2017-win2016
      steps:
      - powershell: |
          Invoke-WebRequest https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz -OutFile boost_1_68_0.tar.gz
          tar xzf boost_1_68_0.tar.gz
        displayName: Get boost
      - powershell: |
          git submodule update --init --recursive
          mkdir $(Build.BinariesDirectory)\build
        displayName: "Prepare build"
      - task: CMake@1
        displayName: "Configure xenium"
        inputs:
          workingDirectory: $(Build.BinariesDirectory)\build
          cmakeArgs: -G "Visual Studio 15 2017 Win64" -DBOOST_ROOT=./boost_1_68_0 -T host=x64 $(Build.SourcesDirectory)
      - task: CMake@1
        displayName: "Build xenium"
        inputs:
          workingDirectory: $(Build.BinariesDirectory)\build
          cmakeArgs: --build . -j 4 --config Debug
      - powershell: |
          gtest
        displayName: "Run tests"
        workingDirectory: $(Build.BinariesDirectory)/build

- stage: Documentation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Documentation
    displayName: "Build + deploy documentation"
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        sudo apt-get install -y doxygen graphviz
      displayName: Apt install dependencies
    - script: |
        cd doc
        doxygen
      displayName: build doxygen
    - script: |
        cd doc/html
        git init
        git checkout --orphan gh-pages
        git add .
        git -c user.name='Azure' -c user.email='Azure' commit -m "Deploy xenium documentation to gh-pages"
        git push -f -q "https://mpoeter:$(GITHUB_TOKEN)@github.com/mpoeter/xenium.git" gh-pages
      displayName: publish GitHub pages
